//! The hub's join-token store (story #163).
//!
//! The pairing model (ADR 0005, unchanged): the operator mints a one-time
//! **join secret** for a unique **label**; a body redeems that secret for a
//! long-lived **credential** and is bound to the token; the operator can
//! list, invalidate, or revoke. The store is a single JSON file,
//! `HOLLER_STATE_DIR/hub/tokens.json`, guarded by an advisory `flock`
//! (`hub/tokens.json.lock`, via `fs4`) around every load-modify-save, so
//! concurrent CLIs and the live hub can never interleave a read and a write
//! and lose a write.
//!
//! Secrets are **never persisted**. At rest the store keeps only
//! `HMAC-SHA-256(pepper, secret)` for the one-time join secret — a redeem
//! recomputes the HMAC of the presented value and compares in constant time.
//! The pepper is env `HOLLER_PEPPER` (hex) or a 32-byte random file
//! `hub/.pepper` (mode 0600), autogenerated on first use by `hub serve` or
//! `hub token mint`.
//!
//! Issue #323 (ADR 0007/0008 amendment): a bound record's credential-proving
//! material is a **public key** (`body_pubkey`), not a shared secret. The
//! body registers it at `circuit/join`; the hub never issues (and the store
//! never holds) a bearer credential — every later reconnect proves possession
//! of the matching private key via the `circuit/authenticate` →
//! `circuit/prove` challenge-response ([`crate::circuit`]). A stolen store
//! therefore yields nothing usable for authentication, not even a digest
//! worth attacking offline.
//!
//! Every operation here is **synchronous** (a `std::flock` held over the
//! blocking read-modify-write). The async wrappers at the bottom of the file
//! (`mint_async` / `redeem_async` / …) run the same work in
//! `tokio::task::spawn_blocking` when the caller is on a tokio runtime —
//! the hub's serve loop is — so the blocking I/O and flock never run on an
//! async executor thread. The CLI's one-shot leaves call the synchronous
//! versions directly (no runtime).

use std::collections::HashMap;
use std::fs::File;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Mutex;
use std::sync::OnceLock;

use hmac::Hmac;
use hmac::Mac;
use sha2::Sha256;
use subtle::ConstantTimeEq;

use holler_proto::log::Component;
use holler_proto::log::Direction;
use holler_proto::log::Event;
use holler_proto::log::Severity;
use holler_proto::RedeemError;
use holler_proto::TokenError;

use crate::state::{ensure_dirs, HubState};

/// The token store file: `<root>/hub/tokens.json`.
pub fn tokens_path(state: &HubState) -> PathBuf {
    state.hub_dir.join("tokens.json")
}

/// The advisory lock that guards the token store: `<root>/hub/tokens.json.lock`.
pub fn tokens_lock_path(state: &HubState) -> PathBuf {
    state.hub_dir.join("tokens.json.lock")
}

/// The autogen pepper file: `<root>/hub/.pepper` (mode 0600).
pub fn pepper_path(state: &HubState) -> PathBuf {
    state.hub_dir.join(".pepper")
}

/// The default join-token time-to-live (the spec's 24 h). Exposed so the CLI
/// and the hub's serve path share one definition of "default".
pub const DEFAULT_TTL: u64 = 24 * 60 * 60;

/// The length, in bytes, of a minted join secret / credential / client id /
/// token id / pepper (256-bit CSPRNG; hex doubles that to the spec's 32-hex).
const SECRET_BYTES: usize = 32;

/// The `flock` a held store lock is represented by. The guard releases the
/// advisory lock on drop.
///
/// **Never deletes the lock file** (issue #301 fixed this — it used to). The
/// lock file must outlive every guard: `flock`'s mutual exclusion is per
/// *inode*, and `acquire_lock` is called fresh (a brand-new `open`, per call)
/// by every contending caller. Deleting the path out from under a lock that
/// is about to be released is a textbook flock+unlink TOCTOU: another
/// caller's `open(&path)` racing that same instant — already in flight,
/// blocked only on `try_lock`, not on `open` — can land *before* the removal
/// (locks the same, still-linked inode, correctly serialized) or *after* it
/// (creates a brand-new inode at that path and trivially "acquires" a lock
/// nobody else holds, since the new inode has never been locked). Once two
/// callers hold "exclusive" locks on two different inodes for what is
/// supposed to be one logical lock, mutual exclusion over `tokens.json` is
/// gone: a `redeem`'s load-mutate-save can interleave with another's and
/// silently lose the loser's write. Measured directly: issue #301's load
/// test (`holler-cli/tests/token_load_test.rs`, 30 real concurrent `body
/// join` subprocesses) reproduced exactly this — one token's successful
/// redeem (the body got its credential) never landed in `tokens.json` (the
/// row stayed `unused`), clobbered by a concurrent redeem's save that had
/// loaded an older snapshot through the very race described above. The lock
/// file itself holds no data (`acquire_lock`'s own comment: "contents are
/// never read"), so leaving it in place forever costs nothing and closes the
/// race for good — every caller now locks the one, permanent inode.
struct StoreLock {
    file: File,
}

impl Drop for StoreLock {
    fn drop(&mut self) {
        // Fully-qualified: use fs4's flock `unlock` (not std's inherent one).
        // The lock *file* is deliberately left in place — see this struct's
        // own doc comment for why removing it here was the bug.
        let _ = fs4::FileExt::unlock(&self.file);
    }
}

/// The three possible shapes of a token's `state` member on the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenState {
    /// Minted, not yet redeemed.
    Unused,
    /// Redeemed by a body; the join secret is consumed.
    Bound,
    /// Inactivated by `delete` / `revoke`.
    Revoked,
}

/// One row of `tokens.json`. `secret_hmac` is the only at-rest secret
/// material (the join secret's HMAC — never the secret itself); `body_pubkey`
/// is a public key, not a secret, so it is kept in the clear (issue #323).
/// `token_id` is the operator-facing id (`tok_<32hex>`).
///
/// (The store serializes records via `serde_json::Value` — see `Store` — so
/// `holler-hub` needs no `serde` derive dependency; the wire shape is defined
/// by the `to_value`/`from_value` pair below.)
#[derive(Debug, Clone, PartialEq)]
pub struct Record {
    /// The operator-facing id: `tok_<32hex>`.
    pub token_id: String,
    /// The unique-per-hub label the token was minted for (ADR 0005).
    pub label: String,
    /// `created` as unix epoch seconds (RFC3339 on the wire is optional; the
    /// spec pins the record to a number).
    pub created: u64,
    /// `expires` as unix epoch seconds.
    pub expires: u64,
    /// `unused` / `bound` / `revoked`.
    pub state: TokenState,
    /// `HMAC-SHA-256(pepper, join_secret)` as hex.
    pub secret_hmac: String,
    /// The body's Ed25519 public key, hex-encoded (issue #323) — registered
    /// at `circuit/join`, never a secret. Present once bound (omitted from
    /// the wire shape when `None` — see `record_to_value`).
    pub body_pubkey: Option<String>,
    /// The body's client id (`cli_<32hex>`). Present once bound.
    pub client_id: Option<String>,
    /// The body's hostname (redeem / live-credential path). Present once bound.
    pub hostname: Option<String>,
    /// The moment the token was redeemed, epoch seconds. Present once bound.
    pub bound_at: Option<u64>,
    /// The most recent live-credential check, epoch seconds.
    pub last_seen: Option<u64>,
}

/// The wire name of a token `state` member (the spec's lowercase strings).
/// Public: the CLI's `hub token list`/`ping` print these on stdout.
pub fn state_str(s: TokenState) -> &'static str {
    match s {
        TokenState::Unused => "unused",
        TokenState::Bound => "bound",
        TokenState::Revoked => "revoked",
    }
}

fn parse_state(s: &str) -> TokenState {
    match s {
        "bound" => TokenState::Bound,
        "revoked" => TokenState::Revoked,
        _ => TokenState::Unused,
    }
}

/// One row's wire shape (the keys the spec pins on the record). `secret_hmac`
/// is a hex digest — never the secret; `body_pubkey` is a public key, kept in
/// the clear.
fn record_to_value(r: &Record) -> serde_json::Value {
    let mut m = serde_json::Map::new();
    m.insert("token_id".into(), serde_json::Value::String(r.token_id.clone()));
    m.insert("label".into(), serde_json::Value::String(r.label.clone()));
    m.insert("created".into(), serde_json::Value::from(r.created));
    m.insert("expires".into(), serde_json::Value::from(r.expires));
    m.insert("state".into(), serde_json::Value::String(state_str(r.state).into()));
    m.insert("secret_hmac".into(), serde_json::Value::String(r.secret_hmac.clone()));
    if let Some(k) = &r.body_pubkey {
        m.insert("body_pubkey".into(), serde_json::Value::String(k.clone()));
    }
    if let Some(c) = &r.client_id {
        m.insert("client_id".into(), serde_json::Value::String(c.clone()));
    }
    if let Some(h) = &r.hostname {
        m.insert("hostname".into(), serde_json::Value::String(h.clone()));
    }
    if let Some(t) = r.bound_at {
        m.insert("bound_at".into(), serde_json::Value::from(t));
    }
    if let Some(t) = r.last_seen {
        m.insert("last_seen".into(), serde_json::Value::from(t));
    }
    serde_json::Value::Object(m)
}

fn record_from_value(v: &serde_json::Value) -> Option<Record> {
    let get = |k: &str| v.get(k).and_then(|x| x.as_str()).map(str::to_string);
    let get_u64 = |k: &str| v.get(k).and_then(|x| x.as_u64());
    let record = Record {
        token_id: get("token_id")?,
        label: get("label")?,
        created: get_u64("created")?,
        expires: get_u64("expires")?,
        state: get("state").map(|s| parse_state(&s)).unwrap_or(TokenState::Unused),
        secret_hmac: get("secret_hmac")?,
        body_pubkey: get("body_pubkey"),
        client_id: get("client_id"),
        hostname: get("hostname"),
        bound_at: get_u64("bound_at"),
        last_seen: get_u64("last_seen"),
    };
    Some(record)
}

/// The in-memory image of `tokens.json`: every record, plus a label → id map
/// that enforces ADR 0005's label uniqueness at mint.
#[derive(Debug, Default)]
struct Store {
    records: Vec<Record>,
    label_to_key: HashMap<String, String>,
}

impl Store {
    /// Load `tokens.json` (empty if absent) and rebuild the label index.
    fn load(path: &Path) -> Result<Store, TokenError> {
        if !path.exists() {
            return Ok(Store::default());
        }
        let raw = std::fs::read_to_string(path)
            .map_err(|e| TokenError::new(format!("cannot read tokens store: {e}")))?;
        let values: Vec<serde_json::Value> =
            serde_json::from_str(&raw).map_err(|e| TokenError::new(format!("tokens store is corrupted: {e}")))?;
        let records: Vec<Record> = values.iter().filter_map(record_from_value).collect();
        let mut label_to_key = HashMap::new();
        for r in &records {
            label_to_key.entry(r.label.clone()).or_insert_with(|| r.token_id.clone());
        }
        Ok(Store {
            records,
            label_to_key,
        })
    }

    /// Persist `records` to `path` (the caller holds the lock).
    fn save(&self, path: &Path) -> Result<(), TokenError> {
        let values: Vec<serde_json::Value> = self.records.iter().map(record_to_value).collect();
        let raw = serde_json::to_string_pretty(&values)
            .map_err(|e| TokenError::new(format!("cannot serialize tokens store: {e}")))?;
        std::fs::write(path, format!("{raw}\n")).map_err(|e| TokenError::new(format!("cannot write tokens store: {e}")))?;
        Ok(())
    }

    fn by_mut(&mut self, token_id: &str) -> Option<&mut Record> {
        self.records.iter_mut().find(|r| r.token_id == token_id)
    }
}

/// Acquire the whole-file advisory lock. On a `WouldBlock` (another hub or
/// CLI holds it) the store is unavailable — that is an error, not a wait:
/// the spec wants concurrent operations to be serialized, not to race a
/// lock the caller will not get.
fn acquire_lock(state: &HubState) -> Result<StoreLock, TokenError> {
    // Ensure `<root>/hub` exists before we open the lock file inside it: a
    // fresh `HOLLER_STATE_DIR` (or a state dir that was never `serve`d) has no
    // `hub/` subdir yet, and `OpenOptions::open` cannot create a missing parent.
    ensure_dirs(state).map_err(|e| TokenError::new(format!("cannot create state dir: {e}")))?;
    let path = tokens_lock_path(state);
    // The lock file's contents are never read; we create (if absent) and write
    // nothing, but must not truncate an existing one (it is only ever empty).
    let file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(false)
        .write(true)
        .open(&path)
        .map_err(|e| TokenError::new(format!("cannot open token lock {}: {e}", path.display())))?;
    // Fully-qualified so we call fs4's flock (not std's inherent `try_lock`,
    // which shadows the trait method and uses a distinct `TryLockError`).
    match fs4::FileExt::try_lock(&file) {
        Ok(()) => Ok(StoreLock { file }),
        Err(fs4::TryLockError::WouldBlock) => Err(TokenError::new(
            "another holler process holds the token lock; retry",
        )),
        Err(e) => Err(TokenError::new(format!(
            "cannot lock token store {}: {e}",
            path.display()
        ))),
    }
}

/// [`acquire_lock`] with a short bounded retry on contention (issue #301).
///
/// `acquire_lock`'s own "an error, not a wait" policy is correct for a
/// one-shot CLI invocation (`hub token mint`/`delete`/`revoke`): a human (or
/// the CLI's own caller-level retry — see `holler-cli/tests/support/mod.rs`'s
/// `mint_token`/`join`) is already in the loop and can just try again a
/// moment later. `redeem` is different: it runs *inside the live hub*, once
/// per `circuit/join`, and a real onboarding batch can legitimately land
/// dozens of those on the hub's own concurrent connection tasks within the
/// same instant — every one of them a distinct, perfectly valid token, not a
/// caller mistake. Measured directly (issue #301's load test,
/// `holler-cli/tests/token_load_test.rs`, 30 real concurrent `body join`
/// subprocesses against one hub): without this, those redemptions lose the
/// non-blocking `try_lock` race against each other's own `redeem` calls and
/// come back `RedeemError::NotFound` ("no matching token") even though the
/// token is real and unredeemed — `redeem`'s blanket `Err(_) =>
/// RedeemError::NotFound` on any lock failure swallowed the real "briefly
/// busy, try again" reason along with genuine "no such token" cases. A short
/// bounded spin here (a few, at most tens of, milliseconds — well under
/// what a real join's own caller would ever notice) resolves the hub's
/// self-contention without touching `acquire_lock`'s contract for its other
/// (CLI, one-shot) callers.
fn acquire_lock_retrying(state: &HubState) -> Result<StoreLock, TokenError> {
    let deadline = std::time::Instant::now() + std::time::Duration::from_millis(2000);
    let mut delay_ms = 2u64;
    loop {
        match acquire_lock(state) {
            Ok(lock) => return Ok(lock),
            Err(e) if e.message.contains("holds the token lock") && std::time::Instant::now() < deadline => {
                std::thread::sleep(std::time::Duration::from_millis(delay_ms));
                delay_ms = (delay_ms * 2).min(50);
            }
            Err(e) => return Err(e),
        }
    }
}

/// The HMAC-SHA-256 of `secret` under `pepper`, as lowercase hex. This is the
/// only form of a secret the store ever holds.
fn hmac_hex(pepper: &[u8], secret: &str) -> Result<String, TokenError> {
    // An HMAC accepts any key length, so `new_from_slice` cannot reject the
    // pepper — but clippy denies `expect`/`panic`, so map the (unreachable)
    // failure to a fail-closed store error instead of aborting.
    let mut mac = Hmac::<Sha256>::new_from_slice(pepper)
        .map_err(|_| TokenError::new("HMAC rejected the pepper key"))?;
    mac.update(secret.as_bytes());
    Ok(hex::encode(mac.finalize().into_bytes()))
}

/// Constant-time compare of two hex digests (the secret is never compared raw).
/// The lengths always match (both are 64-hex SHA-256 digests), so a plain
/// `ct_eq` over the byte slices is well-defined.
fn constant_time_eq(a: &str, b: &str) -> bool {
    a.as_bytes().ct_eq(b.as_bytes()).into()
}

/// The current unix epoch in seconds (the store's clock for `created`/
/// `expires`/`bound_at`/`last_seen`). Public: the CLI's `ping` compares a
/// token's `expires` against the same clock.
///
/// Issue #207: this crate's `Record` fields and `Roster`'s `Clock`/
/// `AtomicU64` machinery are `u64` throughout the on-disk token store, so
/// this keeps its own `u64`-returning signature rather than the `i64` the
/// other four (now deduplicated into [`holler_proto::now_secs`]) settled
/// on — converting the whole persisted-record/roster surface to `i64` is a
/// much bigger change than this issue's "pure refactor, no behavior change"
/// scope. It still delegates to the one shared clock read (`SystemTime::now`
/// is otherwise called nowhere else in the workspace) and casts back to
/// `u64`, which is always safe: unix seconds since 1970 are positive and
/// nowhere near `i64::MAX`.
pub fn now_secs() -> u64 {
    holler_proto::now_secs() as u64
}

/// Draw 256 random bits from the CSPRNG. (Never `panic` — a CSPRNG failure is
/// a fail-closed store error, surfaced as a `TokenError`.)
fn random_bytes() -> Result<Vec<u8>, TokenError> {
    let mut buf = vec![0u8; SECRET_BYTES];
    getrandom::fill(&mut buf).map_err(|e| TokenError::new(format!("CSPRNG failure: {e}")))?;
    Ok(buf)
}

/// A 32-hex id with the given prefix (`tok_` / `cli_`).
fn mint_id(prefix: &str) -> Result<String, TokenError> {
    Ok(format!("{prefix}{}", hex::encode(random_bytes()?)))
}

/// The label grammar (ADR 0005 §1): `^[a-z0-9][a-z0-9-]{0,31}$`.
fn valid_label(label: &str) -> bool {
    if !(1..=32).contains(&label.len()) {
        return false;
    }
    let mut chars = label.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphanumeric() && first.is_ascii_lowercase() || first.is_ascii_digit()) {
        return false;
    }
    chars
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Resolve the effective pepper: env `HOLLER_PEPPER` (hex) wins; else the
/// `hub/.pepper` file; else autogenerate a 32-byte random pepper into
/// `hub/.pepper` (0600) and emit the spec's `pepper_generated` info event.
///
/// The resolution is cached per state dir for the process lifetime — the
/// pepper must not change under a running hub's feet, and re-reading the file
/// on every HMAC would be needless I/O.
fn effective_pepper(state: &HubState) -> Result<Vec<u8>, TokenError> {
    let key = state.root.to_string_lossy().to_string();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let cache = cache
        .lock()
        .unwrap_or_else(|p| p.into_inner());
    if let Some(p) = cache.get(&key) {
        return Ok(p.clone());
    }
    let pepper = resolve_pepper_uncached(state)?;
    drop(cache);
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut cache = cache
        .lock()
        .unwrap_or_else(|p| p.into_inner());
    cache.insert(key, pepper.clone());
    Ok(pepper)
}

/// The cache key is the state dir; the value the effective pepper. (A
/// process-scoped cache — a CLI invocation that changes the env pepper re-runs
/// the resolution because its state dir is typically a different dir, and the
/// hub's dir is stable for its whole life.)
type PepperCache = Mutex<HashMap<String, Vec<u8>>>;
static CACHE: OnceLock<PepperCache> = OnceLock::new();

fn resolve_pepper_uncached(state: &HubState) -> Result<Vec<u8>, TokenError> {
    if let Ok(hex_str) = std::env::var("HOLLER_PEPPER") {
        let bytes = hex::decode(hex_str)
            .map_err(|_| TokenError::new("HOLLER_PEPPER is not valid hex"))?;
        return Ok(bytes);
    }
    let path = pepper_path(state);
    if path.exists() {
        let bytes = std::fs::read(&path)
            .map_err(|e| TokenError::new(format!("cannot read pepper {}: {e}", path.display())))?;
        return Ok(bytes);
    }
    // Neither env nor file: autogenerate. This is the spec's replacement for
    // the old shell-script step.
    let bytes = random_bytes()?;
    std::fs::File::create(&path)
        .map_err(|e| TokenError::new(format!("cannot create pepper {}: {e}", path.display())))?;
    set_mode_0600(&path);
    std::fs::write(&path, &bytes)
        .map_err(|e| TokenError::new(format!("cannot write pepper {}: {e}", path.display())))?;
    emit_pepper_generated();
    Ok(bytes)
}

/// Set a just-created file's mode to 0600 (the pepper is a secret).
#[cfg(unix)]
fn set_mode_0600(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    // `File::create` leaves the mode at the default (0644 & umask); tighten it
    // to owner-only so the pepper is readable by no one else.
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
}

/// No-op on non-Unix (the spec pins 0600 on Unix; elsewhere the OS default stands).
#[cfg(not(unix))]
fn set_mode_0600(_path: &Path) {}

/// Emit the spec's `info pepper_generated` event. The pepper itself is never
/// logged (the redaction in #144 would hide it, but we never hand it to the
/// event at all — only the fact and the path).
fn emit_pepper_generated() {
    let ev = Event {
        component: Component::Token,
        severity: Severity::Info,
        direction: Direction::Local,
        method: "pepper_generated",
        id: None,
        peer: None,
        fields: Vec::new(),
        frame: None,
    };
    holler_proto::log::emit(&ev);
}

/// The result of a successful mint: the stored record **and** the one-time
/// join secret (shown to the operator exactly once, never persisted).
#[derive(Debug, Clone)]
pub struct Minted {
    /// The record as stored (its `secret_hmac`, not the secret).
    pub record: Record,
    /// The join secret (`hlr_join_<64hex>`) — returned once, never persisted.
    pub secret: String,
}

/// Mint a join token for `label` with a TTL of `ttl` seconds.
///
/// Fails closed: an invalid or duplicate label is a [`TokenError`]; the label
/// grammar (ADR 0005) and the uniqueness rule are both enforced here, at mint,
/// under the lock. On success the operator is handed the one-time secret.
pub fn mint(label: &str, ttl_secs: u64, state: &HubState) -> Result<Minted, TokenError> {
    let _lock = acquire_lock(state)?;
    let pepper = effective_pepper(state)?;
    let mut store = Store::load(&tokens_path(state))?;

    if !valid_label(label) {
        return Err(TokenError::new(format!(
            "invalid label {label:?}: must match [a-z0-9][a-z0-9-]{{0,31}}"
        )));
    }
    if store.label_to_key.contains_key(label) {
        return Err(TokenError::new(format!("label {label:?} already in use")));
    }

    let now = now_secs();
    let token_id = mint_id("tok_")?;
    let secret = format!("hlr_join_{}", hex::encode(random_bytes()?));
    let secret_hmac = hmac_hex(&pepper, &secret)?;

    let record = Record {
        token_id: token_id.clone(),
        label: label.to_string(),
        created: now,
        expires: now + ttl_secs,
        state: TokenState::Unused,
        secret_hmac,
        body_pubkey: None,
        client_id: None,
        hostname: None,
        bound_at: None,
        last_seen: None,
    };
    store.records.push(record.clone());
    store.label_to_key.insert(label.to_string(), token_id.clone());
    store.save(&tokens_path(state))?;

    Ok(Minted { record, secret })
}

/// List every record (no secrets — the store never holds them).
pub fn list(state: &HubState) -> Result<Vec<Record>, TokenError> {
    let _lock = acquire_lock(state)?;
    let store = Store::load(&tokens_path(state))?;
    Ok(store.records)
}

/// Inactivate a token: if it is `unused` the join secret is invalid; if it is
/// `bound` the credential is invalid **but the row is kept** (with its
/// hostname / last_seen) so `list` shows who was cut off. The registry story
/// will additionally close the live socket at once.
///
/// Returns the record's new shape. The operator-facing message distinguishes
/// `invalidated` (unused) from `revoked` (bound) in the CLI, not here.
pub fn delete(token_id: &str, state: &HubState) -> Result<Record, TokenError> {
    let _lock = acquire_lock(state)?;
    let mut store = Store::load(&tokens_path(state))?;
    let Some(record) = store.by_mut(token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    record.state = TokenState::Revoked;
    let out = record.clone();
    store.save(&tokens_path(state))?;
    Ok(out)
}

/// Redeem a join secret for a body, registering the body's public key. The
/// secret is hashed with the pepper and matched against every record's
/// `secret_hmac` in constant time.
///
/// On success the token moves to `bound` (its `client_id`, `hostname`,
/// `body_pubkey`, and `bound_at` are set) and the join secret is **consumed**
/// (a second redeem is [`RedeemError::AlreadyBound`]). Issue #323: the hub
/// mints no credential — the returned `client_id` is all the body needs; it
/// authenticates every later reconnect by proving possession of the private
/// key matching `body_pubkey` (`circuit/authenticate` → `circuit/prove`).
/// Exactly one concurrent winner is guaranteed by the whole-file flock held
/// across the read-modify-write.
///
/// Uses [`acquire_lock_retrying`] rather than the bare [`acquire_lock`]
/// (issue #301): unlike `mint`/`delete`/`revoke` (one-shot CLI invocations
/// where the operator is already the retry loop), `redeem` runs inside the
/// live hub once per `circuit/join`, so a real onboarding batch's own
/// concurrent joins race *each other*'s `redeem` calls for this same lock —
/// see that function's doc for the measured failure this replaced
/// (legitimate, distinct, unredeemed tokens wrongly reported `NotFound`).
pub fn redeem(
    secret: &str,
    hostname: &str,
    body_pubkey: &str,
    state: &HubState,
) -> Result<String, RedeemError> {
    let _lock = match acquire_lock_retrying(state) {
        Ok(g) => g,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let pepper = match effective_pepper(state) {
        Ok(p) => p,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let presented = match hmac_hex(&pepper, secret) {
        Ok(p) => p,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let mut store = match Store::load(&tokens_path(state)) {
        Ok(s) => s,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let now = now_secs();

    for record in store.records.iter_mut() {
        if !constant_time_eq(&presented, &record.secret_hmac) {
            continue;
        }
        match record.state {
            TokenState::Unused => {
                if record.expires < now {
                    return Err(RedeemError::Expired);
                }
                let client_id = match mint_id("cli_") {
                    Ok(id) => id,
                    Err(_) => return Err(RedeemError::NotFound),
                };
                record.body_pubkey = Some(body_pubkey.to_string());
                record.client_id = Some(client_id.clone());
                record.hostname = Some(hostname.to_string());
                record.bound_at = Some(now);
                record.state = TokenState::Bound;
                if store.save(&tokens_path(state)).is_err() {
                    return Err(RedeemError::NotFound);
                }
                return Ok(client_id);
            }
            TokenState::Bound => return Err(RedeemError::AlreadyBound),
            TokenState::Revoked => return Err(RedeemError::Revoked),
        }
    }
    Err(RedeemError::NotFound)
}

/// The step-1 half of `circuit/authenticate` (issue #323): resolve a bound,
/// live-eligible token record. Fails closed: a token that is unknown, not
/// `bound`, expired, or `revoked` is a no-match, folded into one
/// [`TokenError`] (the caller — [`crate::circuit::verify_and_authenticate`] —
/// maps any failure here to the wire's `-32002 unauthenticated`, never
/// distinguishing *why* to a peer that has not yet proven anything).
///
/// Called again at step 2 (after the body's `circuit/prove`) to catch a
/// revoke/expiry race between the challenge and the proof — the nonce
/// challenge issued at step 1 carries no authority of its own; only a record
/// that is *still* bound at the moment the signature is checked lets the
/// connection through.
pub fn bound_record(token_id: &str, state: &HubState) -> Result<Record, TokenError> {
    let _lock = acquire_lock(state)?;
    let store = Store::load(&tokens_path(state))?;
    let now = now_secs();
    let Some(record) = store.records.iter().find(|r| r.token_id == token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    if record.state != TokenState::Bound {
        return Err(TokenError::new(format!("token {token_id} is not bound")));
    }
    if record.expires < now {
        return Err(TokenError::new(format!("token {token_id} is expired")));
    }
    if record.body_pubkey.is_none() {
        return Err(TokenError::new(format!("token {token_id} has no public key on record")));
    }
    Ok(record.clone())
}

/// Bump a token's `last_seen` (a live presence beat from the bound body).
/// Fails closed if the token is missing or not bound.
pub fn touch_last_seen(token_id: &str, state: &HubState) -> Result<(), TokenError> {
    let _lock = acquire_lock(state)?;
    let mut store = Store::load(&tokens_path(state))?;
    let Some(record) = store.by_mut(token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    if record.state != TokenState::Bound {
        return Err(TokenError::new(format!("token {token_id} is not bound")));
    }
    record.last_seen = Some(now_secs());
    store.save(&tokens_path(state))
}

// --- async wrappers (spawn_blocking) -------------------------------------
//
// The hub's serve loop is a tokio runtime; running the blocking `flock` +
// file I/O above directly on an executor thread would starve it. Every
// operation the serve path needs therefore has an async twin that runs the
// same synchronous work in `tokio::task::spawn_blocking` — a dedicated
// blocking-pool thread, never the calling task's own executor thread (issue
// #184's spec test, `slow_token_store_does_not_stall_sibling_ping`, is what
// pins this: these wrappers previously used `block_in_place`, which runs the
// blocking work *on the current worker thread* and only compensates by
// spinning up a replacement worker — correct on a multi-threaded runtime in
// practice, but not what the spec asks for, and one more thing to get subtly
// wrong under a constrained worker-thread count. `spawn_blocking` is the
// unambiguous version of "never runs on an executor thread"). The CLI's
// one-shot leaves have no runtime and call the synchronous fns directly.
//
// A `spawn_blocking` join failure (the blocking task panicked) is
// unreachable in practice — none of `mint`/`redeem`/`bound_record` ever
// panics, they return `Result` — so it is mapped to a fail-closed
// `TokenError`/`RedeemError::NotFound` rather than surfaced as a distinct
// variant nobody could usefully handle.

/// `mint` on the blocking pool (the spec: "all locked operations run in
/// `tokio::task::spawn_blocking` when called from async code").
pub async fn mint_async(label: &str, ttl_secs: u64, state: &HubState) -> Result<Minted, TokenError> {
    let (label, state) = (label.to_string(), state.clone());
    tokio::task::spawn_blocking(move || mint(&label, ttl_secs, &state))
        .await
        .unwrap_or_else(|_| Err(TokenError::new("token store task panicked")))
}

/// `redeem` on the blocking pool.
pub async fn redeem_async(
    secret: &str,
    hostname: &str,
    body_pubkey: &str,
    state: &HubState,
) -> Result<String, RedeemError> {
    let (secret, hostname, body_pubkey) = (secret.to_string(), hostname.to_string(), body_pubkey.to_string());
    let state = state.clone();
    tokio::task::spawn_blocking(move || redeem(&secret, &hostname, &body_pubkey, &state))
        .await
        .unwrap_or(Err(RedeemError::NotFound))
}

/// `bound_record` on the blocking pool.
pub async fn bound_record_async(token_id: &str, state: &HubState) -> Result<Record, TokenError> {
    let token_id = token_id.to_string();
    let state = state.clone();
    tokio::task::spawn_blocking(move || {
        // Issue #184's `slow_token_store_does_not_stall_sibling_ping` test
        // hook: an artificial delay on the *blocking-pool* thread only,
        // gated behind the same `HOLLER_TEST_HOOKS=1` flag issue #192's
        // `control/test_drop` uses — a production hub never reads this var
        // as anything but absent. Simulates a slow store (e.g. contended
        // disk) without needing a real one.
        if std::env::var("HOLLER_TEST_HOOKS").as_deref() == Ok("1") {
            if let Some(ms) = std::env::var("HOLLER_TEST_TOKEN_STORE_DELAY_MS").ok().and_then(|s| s.parse().ok()) {
                std::thread::sleep(std::time::Duration::from_millis(ms));
            }
        }
        bound_record(&token_id, &state)
    })
    .await
    .unwrap_or_else(|_| Err(TokenError::new("token store task panicked")))
}
