//! The hub's join-token store (story #163).
//!
//! The pairing model (ADR 0005, unchanged): the operator mints a one-time
//! **join secret** for a unique **label**; a body redeems that secret for a
//! long-lived **credential** and is bound to the token; the operator can
//! list, invalidate, or revoke. The store is a single JSON file,
//! `HOLLER_STATE_DIR/hub/tokens.json`, guarded by an advisory `flock`
//! (`hub/tokens.json.lock`, via `fs4`) around every load-modify-save, so
//! concurrent CLIs and the live hub can never interleave a read and a write
//! and lose a write.
//!
//! Secrets are **never persisted**. At rest the store keeps only
//! `HMAC-SHA-256(pepper, secret)` for the join secret and the credential; a
//! redeem or a live-credential check recomputes the HMAC of the presented
//! value and compares in constant time. The pepper is env `HOLLER_PEPPER`
//! (hex) or a 32-byte random file `hub/.pepper` (mode 0600), autogenerated on
//! first use by `hub serve` or `hub token mint`.
//!
//! Every operation here is **synchronous** (a `std::flock` held over the
//! blocking read-modify-write). The async wrappers at the bottom of the file
//! (`mint_async` / `redeem_async` / …) run the same work in
//! `tokio::task::spawn_blocking` when the caller is on a tokio runtime —
//! the hub's serve loop is — so the blocking I/O and flock never run on an
//! async executor thread. The CLI's one-shot leaves call the synchronous
//! versions directly (no runtime).

use std::collections::HashMap;
use std::fs::File;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Mutex;
use std::sync::OnceLock;
use std::time::SystemTime;
use std::time::UNIX_EPOCH;

use hmac::Hmac;
use hmac::Mac;
use sha2::Sha256;
use subtle::ConstantTimeEq;
use tokio::task::block_in_place;

use holler_proto::log::Component;
use holler_proto::log::Direction;
use holler_proto::log::Event;
use holler_proto::log::Severity;
use holler_proto::RedeemError;
use holler_proto::TokenError;

use crate::state::{ensure_dirs, HubState};

/// The token store file: `<root>/hub/tokens.json`.
pub fn tokens_path(state: &HubState) -> PathBuf {
    state.hub_dir.join("tokens.json")
}

/// The advisory lock that guards the token store: `<root>/hub/tokens.json.lock`.
pub fn tokens_lock_path(state: &HubState) -> PathBuf {
    state.hub_dir.join("tokens.json.lock")
}

/// The autogen pepper file: `<root>/hub/.pepper` (mode 0600).
pub fn pepper_path(state: &HubState) -> PathBuf {
    state.hub_dir.join(".pepper")
}

/// The default join-token time-to-live (the spec's 24 h). Exposed so the CLI
/// and the hub's serve path share one definition of "default".
pub const DEFAULT_TTL: u64 = 24 * 60 * 60;

/// The length, in bytes, of a minted join secret / credential / client id /
/// token id / pepper (256-bit CSPRNG; hex doubles that to the spec's 32-hex).
const SECRET_BYTES: usize = 32;

/// The `flock` a held store lock is represented by. The guard releases the
/// advisory lock (and removes the lock file) on drop.
struct StoreLock {
    file: File,
    path: PathBuf,
}

impl Drop for StoreLock {
    fn drop(&mut self) {
        // Fully-qualified: use fs4's flock `unlock` (not std's inherent one).
        let _ = fs4::FileExt::unlock(&self.file);
        let _ = std::fs::remove_file(&self.path);
    }
}

/// The three possible shapes of a token's `state` member on the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenState {
    /// Minted, not yet redeemed.
    Unused,
    /// Redeemed by a body; the join secret is consumed.
    Bound,
    /// Inactivated by `delete` / `revoke`.
    Revoked,
}

/// One row of `tokens.json`. The at-rest fields are `secret_hmac` and
/// (optionally) `credential_hmac` — **never** the secret or credential
/// themselves. `token_id` is the operator-facing id (`tok_<32hex>`).
///
/// (The store serializes records via `serde_json::Value` — see `Store` — so
/// `holler-hub` needs no `serde` derive dependency; the wire shape is defined
/// by the `to_value`/`from_value` pair below.)
#[derive(Debug, Clone, PartialEq)]
pub struct Record {
    /// The operator-facing id: `tok_<32hex>`.
    pub token_id: String,
    /// The unique-per-hub label the token was minted for (ADR 0005).
    pub label: String,
    /// `created` as unix epoch seconds (RFC3339 on the wire is optional; the
    /// spec pins the record to a number).
    pub created: u64,
    /// `expires` as unix epoch seconds.
    pub expires: u64,
    /// `unused` / `bound` / `revoked`.
    pub state: TokenState,
    /// `HMAC-SHA-256(pepper, join_secret)` as hex.
    pub secret_hmac: String,
    /// `HMAC-SHA-256(pepper, credential)` as hex. Present once bound (omitted
    /// from the wire shape when `None` — see `record_to_value`).
    pub credential_hmac: Option<String>,
    /// The body's client id (`cli_<32hex>`). Present once bound.
    pub client_id: Option<String>,
    /// The body's hostname (redeem / live-credential path). Present once bound.
    pub hostname: Option<String>,
    /// The moment the token was redeemed, epoch seconds. Present once bound.
    pub bound_at: Option<u64>,
    /// The most recent live-credential check, epoch seconds.
    pub last_seen: Option<u64>,
}

/// The wire name of a token `state` member (the spec's lowercase strings).
/// Public: the CLI's `hub token list`/`ping` print these on stdout.
pub fn state_str(s: TokenState) -> &'static str {
    match s {
        TokenState::Unused => "unused",
        TokenState::Bound => "bound",
        TokenState::Revoked => "revoked",
    }
}

fn parse_state(s: &str) -> TokenState {
    match s {
        "bound" => TokenState::Bound,
        "revoked" => TokenState::Revoked,
        _ => TokenState::Unused,
    }
}

/// One row's wire shape (the keys the spec pins on the record). `secret_hmac`
/// and `credential_hmac` are hex digests — never the secrets.
fn record_to_value(r: &Record) -> serde_json::Value {
    let mut m = serde_json::Map::new();
    m.insert("token_id".into(), serde_json::Value::String(r.token_id.clone()));
    m.insert("label".into(), serde_json::Value::String(r.label.clone()));
    m.insert("created".into(), serde_json::Value::from(r.created));
    m.insert("expires".into(), serde_json::Value::from(r.expires));
    m.insert("state".into(), serde_json::Value::String(state_str(r.state).into()));
    m.insert("secret_hmac".into(), serde_json::Value::String(r.secret_hmac.clone()));
    if let Some(c) = &r.credential_hmac {
        m.insert("credential_hmac".into(), serde_json::Value::String(c.clone()));
    }
    if let Some(c) = &r.client_id {
        m.insert("client_id".into(), serde_json::Value::String(c.clone()));
    }
    if let Some(h) = &r.hostname {
        m.insert("hostname".into(), serde_json::Value::String(h.clone()));
    }
    if let Some(t) = r.bound_at {
        m.insert("bound_at".into(), serde_json::Value::from(t));
    }
    if let Some(t) = r.last_seen {
        m.insert("last_seen".into(), serde_json::Value::from(t));
    }
    serde_json::Value::Object(m)
}

fn record_from_value(v: &serde_json::Value) -> Option<Record> {
    let get = |k: &str| v.get(k).and_then(|x| x.as_str()).map(str::to_string);
    let get_u64 = |k: &str| v.get(k).and_then(|x| x.as_u64());
    let record = Record {
        token_id: get("token_id")?,
        label: get("label")?,
        created: get_u64("created")?,
        expires: get_u64("expires")?,
        state: get("state").map(|s| parse_state(&s)).unwrap_or(TokenState::Unused),
        secret_hmac: get("secret_hmac")?,
        credential_hmac: get("credential_hmac"),
        client_id: get("client_id"),
        hostname: get("hostname"),
        bound_at: get_u64("bound_at"),
        last_seen: get_u64("last_seen"),
    };
    Some(record)
}

/// The in-memory image of `tokens.json`: every record, plus a label → id map
/// that enforces ADR 0005's label uniqueness at mint.
#[derive(Debug, Default)]
struct Store {
    records: Vec<Record>,
    label_to_key: HashMap<String, String>,
}

impl Store {
    /// Load `tokens.json` (empty if absent) and rebuild the label index.
    fn load(path: &Path) -> Result<Store, TokenError> {
        if !path.exists() {
            return Ok(Store::default());
        }
        let raw = std::fs::read_to_string(path)
            .map_err(|e| TokenError::new(format!("cannot read tokens store: {e}")))?;
        let values: Vec<serde_json::Value> =
            serde_json::from_str(&raw).map_err(|e| TokenError::new(format!("tokens store is corrupted: {e}")))?;
        let records: Vec<Record> = values.iter().filter_map(record_from_value).collect();
        let mut label_to_key = HashMap::new();
        for r in &records {
            label_to_key.entry(r.label.clone()).or_insert_with(|| r.token_id.clone());
        }
        Ok(Store {
            records,
            label_to_key,
        })
    }

    /// Persist `records` to `path` (the caller holds the lock).
    fn save(&self, path: &Path) -> Result<(), TokenError> {
        let values: Vec<serde_json::Value> = self.records.iter().map(record_to_value).collect();
        let raw = serde_json::to_string_pretty(&values)
            .map_err(|e| TokenError::new(format!("cannot serialize tokens store: {e}")))?;
        std::fs::write(path, format!("{raw}\n")).map_err(|e| TokenError::new(format!("cannot write tokens store: {e}")))?;
        Ok(())
    }

    fn by_mut(&mut self, token_id: &str) -> Option<&mut Record> {
        self.records.iter_mut().find(|r| r.token_id == token_id)
    }
}

/// Acquire the whole-file advisory lock. On a `WouldBlock` (another hub or
/// CLI holds it) the store is unavailable — that is an error, not a wait:
/// the spec wants concurrent operations to be serialized, not to race a
/// lock the caller will not get.
fn acquire_lock(state: &HubState) -> Result<StoreLock, TokenError> {
    // Ensure `<root>/hub` exists before we open the lock file inside it: a
    // fresh `HOLLER_STATE_DIR` (or a state dir that was never `serve`d) has no
    // `hub/` subdir yet, and `OpenOptions::open` cannot create a missing parent.
    ensure_dirs(state).map_err(|e| TokenError::new(format!("cannot create state dir: {e}")))?;
    let path = tokens_lock_path(state);
    // The lock file's contents are never read; we create (if absent) and write
    // nothing, but must not truncate an existing one (it is only ever empty).
    let file = std::fs::OpenOptions::new()
        .create(true)
        .truncate(false)
        .write(true)
        .open(&path)
        .map_err(|e| TokenError::new(format!("cannot open token lock {}: {e}", path.display())))?;
    // Fully-qualified so we call fs4's flock (not std's inherent `try_lock`,
    // which shadows the trait method and uses a distinct `TryLockError`).
    match fs4::FileExt::try_lock(&file) {
        Ok(()) => Ok(StoreLock {
            file,
            path,
        }),
        Err(fs4::TryLockError::WouldBlock) => Err(TokenError::new(
            "another holler process holds the token lock; retry",
        )),
        Err(e) => Err(TokenError::new(format!(
            "cannot lock token store {}: {e}",
            path.display()
        ))),
    }
}

/// The HMAC-SHA-256 of `secret` under `pepper`, as lowercase hex. This is the
/// only form of a secret the store ever holds.
fn hmac_hex(pepper: &[u8], secret: &str) -> Result<String, TokenError> {
    // An HMAC accepts any key length, so `new_from_slice` cannot reject the
    // pepper — but clippy denies `expect`/`panic`, so map the (unreachable)
    // failure to a fail-closed store error instead of aborting.
    let mut mac = Hmac::<Sha256>::new_from_slice(pepper)
        .map_err(|_| TokenError::new("HMAC rejected the pepper key"))?;
    mac.update(secret.as_bytes());
    Ok(hex::encode(mac.finalize().into_bytes()))
}

/// Constant-time compare of two hex digests (the secret is never compared raw).
/// The lengths always match (both are 64-hex SHA-256 digests), so a plain
/// `ct_eq` over the byte slices is well-defined.
fn constant_time_eq(a: &str, b: &str) -> bool {
    a.as_bytes().ct_eq(b.as_bytes()).into()
}

/// The current unix epoch in seconds (the store's clock for `created`/
/// `expires`/`bound_at`/`last_seen`). Public: the CLI's `ping` compares a
/// token's `expires` against the same clock.
pub fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Draw 256 random bits from the CSPRNG. (Never `panic` — a CSPRNG failure is
/// a fail-closed store error, surfaced as a `TokenError`.)
fn random_bytes() -> Result<Vec<u8>, TokenError> {
    let mut buf = vec![0u8; SECRET_BYTES];
    getrandom::fill(&mut buf).map_err(|e| TokenError::new(format!("CSPRNG failure: {e}")))?;
    Ok(buf)
}

/// A 32-hex id with the given prefix (`tok_` / `cli_`).
fn mint_id(prefix: &str) -> Result<String, TokenError> {
    Ok(format!("{prefix}{}", hex::encode(random_bytes()?)))
}

/// The label grammar (ADR 0005 §1): `^[a-z0-9][a-z0-9-]{0,31}$`.
fn valid_label(label: &str) -> bool {
    if !(1..=32).contains(&label.len()) {
        return false;
    }
    let mut chars = label.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphanumeric() && first.is_ascii_lowercase() || first.is_ascii_digit()) {
        return false;
    }
    chars
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Resolve the effective pepper: env `HOLLER_PEPPER` (hex) wins; else the
/// `hub/.pepper` file; else autogenerate a 32-byte random pepper into
/// `hub/.pepper` (0600) and emit the spec's `pepper_generated` info event.
///
/// The resolution is cached per state dir for the process lifetime — the
/// pepper must not change under a running hub's feet, and re-reading the file
/// on every HMAC would be needless I/O.
fn effective_pepper(state: &HubState) -> Result<Vec<u8>, TokenError> {
    let key = state.root.to_string_lossy().to_string();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let cache = cache
        .lock()
        .unwrap_or_else(|p| p.into_inner());
    if let Some(p) = cache.get(&key) {
        return Ok(p.clone());
    }
    let pepper = resolve_pepper_uncached(state)?;
    drop(cache);
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut cache = cache
        .lock()
        .unwrap_or_else(|p| p.into_inner());
    cache.insert(key, pepper.clone());
    Ok(pepper)
}

/// The cache key is the state dir; the value the effective pepper. (A
/// process-scoped cache — a CLI invocation that changes the env pepper re-runs
/// the resolution because its state dir is typically a different dir, and the
/// hub's dir is stable for its whole life.)
type PepperCache = Mutex<HashMap<String, Vec<u8>>>;
static CACHE: OnceLock<PepperCache> = OnceLock::new();

fn resolve_pepper_uncached(state: &HubState) -> Result<Vec<u8>, TokenError> {
    if let Ok(hex_str) = std::env::var("HOLLER_PEPPER") {
        let bytes = hex::decode(hex_str)
            .map_err(|_| TokenError::new("HOLLER_PEPPER is not valid hex"))?;
        return Ok(bytes);
    }
    let path = pepper_path(state);
    if path.exists() {
        let bytes = std::fs::read(&path)
            .map_err(|e| TokenError::new(format!("cannot read pepper {}: {e}", path.display())))?;
        return Ok(bytes);
    }
    // Neither env nor file: autogenerate. This is the spec's replacement for
    // the old shell-script step.
    let bytes = random_bytes()?;
    std::fs::File::create(&path)
        .map_err(|e| TokenError::new(format!("cannot create pepper {}: {e}", path.display())))?;
    set_mode_0600(&path);
    std::fs::write(&path, &bytes)
        .map_err(|e| TokenError::new(format!("cannot write pepper {}: {e}", path.display())))?;
    emit_pepper_generated();
    Ok(bytes)
}

/// Set a just-created file's mode to 0600 (the pepper is a secret).
#[cfg(unix)]
fn set_mode_0600(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    // `File::create` leaves the mode at the default (0644 & umask); tighten it
    // to owner-only so the pepper is readable by no one else.
    let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
}

/// No-op on non-Unix (the spec pins 0600 on Unix; elsewhere the OS default stands).
#[cfg(not(unix))]
fn set_mode_0600(_path: &Path) {}

/// Emit the spec's `info pepper_generated` event. The pepper itself is never
/// logged (the redaction in #144 would hide it, but we never hand it to the
/// event at all — only the fact and the path).
fn emit_pepper_generated() {
    let ev = Event {
        component: Component::Token,
        severity: Severity::Info,
        direction: Direction::Local,
        method: "pepper_generated",
        id: None,
        peer: None,
        fields: Vec::new(),
        frame: None,
    };
    holler_proto::log::emit(&ev);
}

/// The result of a successful mint: the stored record **and** the one-time
/// join secret (shown to the operator exactly once, never persisted).
#[derive(Debug, Clone)]
pub struct Minted {
    /// The record as stored (its `secret_hmac`, not the secret).
    pub record: Record,
    /// The join secret (`hlr_join_<64hex>`) — returned once, never persisted.
    pub secret: String,
}

/// Mint a join token for `label` with a TTL of `ttl` seconds.
///
/// Fails closed: an invalid or duplicate label is a [`TokenError`]; the label
/// grammar (ADR 0005) and the uniqueness rule are both enforced here, at mint,
/// under the lock. On success the operator is handed the one-time secret.
pub fn mint(label: &str, ttl_secs: u64, state: &HubState) -> Result<Minted, TokenError> {
    let _lock = acquire_lock(state)?;
    let pepper = effective_pepper(state)?;
    let mut store = Store::load(&tokens_path(state))?;

    if !valid_label(label) {
        return Err(TokenError::new(format!(
            "invalid label {label:?}: must match [a-z0-9][a-z0-9-]{{0,31}}"
        )));
    }
    if store.label_to_key.contains_key(label) {
        return Err(TokenError::new(format!("label {label:?} already in use")));
    }

    let now = now_secs();
    let token_id = mint_id("tok_")?;
    let secret = format!("hlr_join_{}", hex::encode(random_bytes()?));
    let secret_hmac = hmac_hex(&pepper, &secret)?;

    let record = Record {
        token_id: token_id.clone(),
        label: label.to_string(),
        created: now,
        expires: now + ttl_secs,
        state: TokenState::Unused,
        secret_hmac,
        credential_hmac: None,
        client_id: None,
        hostname: None,
        bound_at: None,
        last_seen: None,
    };
    store.records.push(record.clone());
    store.label_to_key.insert(label.to_string(), token_id.clone());
    store.save(&tokens_path(state))?;

    Ok(Minted { record, secret })
}

/// List every record (no secrets — the store never holds them).
pub fn list(state: &HubState) -> Result<Vec<Record>, TokenError> {
    let _lock = acquire_lock(state)?;
    let store = Store::load(&tokens_path(state))?;
    Ok(store.records)
}

/// Inactivate a token: if it is `unused` the join secret is invalid; if it is
/// `bound` the credential is invalid **but the row is kept** (with its
/// hostname / last_seen) so `list` shows who was cut off. The registry story
/// will additionally close the live socket at once.
///
/// Returns the record's new shape. The operator-facing message distinguishes
/// `invalidated` (unused) from `revoked` (bound) in the CLI, not here.
pub fn delete(token_id: &str, state: &HubState) -> Result<Record, TokenError> {
    let _lock = acquire_lock(state)?;
    let mut store = Store::load(&tokens_path(state))?;
    let Some(record) = store.by_mut(token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    record.state = TokenState::Revoked;
    let out = record.clone();
    store.save(&tokens_path(state))?;
    Ok(out)
}

/// Redeem a join secret for a body. The secret is hashed with the pepper and
/// matched against every record's `secret_hmac` in constant time.
///
/// On success the token moves to `bound` (its `client_id`, `hostname`, and
/// `bound_at` are set), the join secret is **consumed** (a second redeem is
/// [`RedeemError::AlreadyBound`]), and the newly-minted credential is returned
/// to the body. Exactly one concurrent winner is guaranteed by the whole-file
/// flock held across the read-modify-write.
pub fn redeem(
    secret: &str,
    hostname: &str,
    state: &HubState,
) -> Result<(String, String), RedeemError> {
    let _lock = match acquire_lock(state) {
        Ok(g) => g,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let pepper = match effective_pepper(state) {
        Ok(p) => p,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let presented = match hmac_hex(&pepper, secret) {
        Ok(p) => p,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let mut store = match Store::load(&tokens_path(state)) {
        Ok(s) => s,
        Err(_) => return Err(RedeemError::NotFound),
    };
    let now = now_secs();

    for record in store.records.iter_mut() {
        if !constant_time_eq(&presented, &record.secret_hmac) {
            continue;
        }
        match record.state {
            TokenState::Unused => {
                if record.expires < now {
                    return Err(RedeemError::Expired);
                }
                let client_id = match mint_id("cli_") {
                    Ok(id) => id,
                    Err(_) => return Err(RedeemError::NotFound),
                };
                let credential = match random_bytes() {
                    Ok(b) => format!("hlr_live_{}", hex::encode(b)),
                    Err(_) => return Err(RedeemError::NotFound),
                };
                record.credential_hmac =
                    Some(hmac_hex(&pepper, &credential).unwrap_or_default());
                record.client_id = Some(client_id.clone());
                record.hostname = Some(hostname.to_string());
                record.bound_at = Some(now);
                record.state = TokenState::Bound;
                if store.save(&tokens_path(state)).is_err() {
                    return Err(RedeemError::NotFound);
                }
                return Ok((client_id, credential));
            }
            TokenState::Bound => return Err(RedeemError::AlreadyBound),
            TokenState::Revoked => return Err(RedeemError::Revoked),
        }
    }
    Err(RedeemError::NotFound)
}

/// Check a live credential against a token. Fails closed: a token that is not
/// `bound`, is expired, or whose credential does not match is a no-match. On a
/// match the record's `last_seen` is bumped (persisted) and returned.
pub fn verify_credential(
    token_id: &str,
    credential: &str,
    state: &HubState,
) -> Result<Record, TokenError> {
    let _lock = acquire_lock(state)?;
    let pepper = effective_pepper(state)?;
    let presented = hmac_hex(&pepper, credential)?;
    let mut store = Store::load(&tokens_path(state))?;
    let now = now_secs();
    let Some(record) = store.by_mut(token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    if record.state != TokenState::Bound {
        return Err(TokenError::new(format!("token {token_id} is not bound")));
    }
    if record.expires < now {
        return Err(TokenError::new(format!("token {token_id} is expired")));
    }
    let Some(stored) = &record.credential_hmac else {
        return Err(TokenError::new(format!("token {token_id} has no credential")));
    };
    if !constant_time_eq(&presented, stored) {
        return Err(TokenError::new("credential does not match"));
    }
    record.last_seen = Some(now);
    let out = record.clone();
    store.save(&tokens_path(state))?;
    Ok(out)
}

/// Bump a token's `last_seen` (a live presence beat from the bound body).
/// Fails closed if the token is missing or not bound.
pub fn touch_last_seen(token_id: &str, state: &HubState) -> Result<(), TokenError> {
    let _lock = acquire_lock(state)?;
    let mut store = Store::load(&tokens_path(state))?;
    let Some(record) = store.by_mut(token_id) else {
        return Err(TokenError::new(format!("no such token {token_id}")));
    };
    if record.state != TokenState::Bound {
        return Err(TokenError::new(format!("token {token_id} is not bound")));
    }
    record.last_seen = Some(now_secs());
    store.save(&tokens_path(state))
}

// --- async wrappers (spawn_blocking) -------------------------------------
//
// The hub's serve loop is a tokio runtime; running the blocking `flock` +
// file I/O above directly on an executor thread would starve it. Every
// operation the serve path needs therefore has an async twin that runs the
// same synchronous work in `tokio::task::spawn_blocking`. (The CLI's
// one-shot leaves have no runtime and call the synchronous fns directly.)

/// `mint` on the blocking pool (the spec: "all locked operations run in
/// `tokio::task::spawn_blocking` when called from async code").
pub async fn mint_async(label: &str, ttl_secs: u64, state: &HubState) -> Result<Minted, TokenError> {
    let (label, state) = (label.to_string(), state.clone());
    block_in_place(|| mint(&label, ttl_secs, &state))
}

/// A test-only knob (story #184): `HOLLER_STORE_DELAY_MS` makes the async store
/// twins wait that many milliseconds before running the (real) work, so a test
/// can simulate a slow token store. Unset (or non-numeric) means no delay. It
/// is a plain `tokio::time::sleep` on the async task (not inside the blocking
/// call), so it never holds the store flock and never starves the runtime.
fn store_delay() -> Option<std::time::Duration> {
    std::env::var("HOLLER_STORE_DELAY_MS")
        .ok()
        .and_then(|s| s.parse().ok())
        .map(std::time::Duration::from_millis)
}

/// `redeem` on the blocking pool.
pub async fn redeem_async(
    secret: &str,
    hostname: &str,
    state: &HubState,
) -> Result<(String, String), RedeemError> {
    let (secret, hostname) = (secret.to_string(), hostname.to_string());
    let state = state.clone();
    if let Some(d) = store_delay() {
        tokio::time::sleep(d).await;
    }
    block_in_place(|| redeem(&secret, &hostname, &state))
}

/// `verify_credential` on the blocking pool.
pub async fn verify_credential_async(
    token_id: &str,
    credential: &str,
    state: &HubState,
) -> Result<Record, TokenError> {
    let (token_id, credential) = (token_id.to_string(), credential.to_string());
    let state = state.clone();
    if let Some(d) = store_delay() {
        tokio::time::sleep(d).await;
    }
    block_in_place(|| verify_credential(&token_id, &credential, &state))
}
